package test

//token live time = 1 month after generated by author (11 oct 2021)
const TOKEN_ONE_MONTH_EXP = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkX2F0IjoxNjM2NTQ5NDc0LCJ1c2VyX2lkIjoxfQ.YU8oQ0nhoEgjdrmYddiKzBeevCV4an4PIjgT6XesQpI"
